### PR TITLE
platform: posix: dma: place api in iterable section

### PR DESCRIPTION
**Pull request by jilaypandya**
this commit refactors dma_driver_api in iterable_section

### CODE REVIEW

**Review by pdgendt — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Review by josuah — APPROVED** [review]

**Comment by kv2019i** [comment]
Ok with the change, but what's the rationale for submitting here and not upstream SOF? https://github.com/thesofproject/sof/

**Comment by pdgendt** [comment]
> Ok with the change, but what's the rationale for submitting here and not upstream SOF? [thesofproject/sof](https://github.com/thesofproject/sof/)

There's currently a difference between this repo, with branch `zephyr` and upstream branch `main`, how does this work to land in this repository (which is the one referenced in the zephyr manifest)?

**Comment by pdgendt** [comment]
@jilaypandya can you create a PR for upstream instead?

**Comment by jilaypandya** [comment]
created a pr for upstream https://github.com/thesofproject/sof/pull/9710 :-)

**Pull request closed without merging**
