### PR TITLE
app: Switch main return type to 'int'

### PR DESCRIPTION
**Pull request by keith-packard**
With Zephyr adopting a different type for 'main', adapt this application to match.

### CODE REVIEW

**Review by stephanosio — APPROVED** [review]

**Comment by marc-hb** [comment]
@keith-packard would you mind submitting this to SOF upstream? This would save some branching. I gave it a try and it looks like the actual SOF firmware (as opposed to the Zephyr test code) does not care about the main function at all:

- https://github.com/thesofproject/sof/pull/7543

**Comment by keith-packard** [comment]
> @keith-packard would you mind submitting this to SOF upstream? This would save some branching. I gave it a try and it looks like the actual SOF firmware (as opposed to the Zephyr test code) does not care about the main function at all:
> 
>     * [TEST IGNORE app: Switch main return type to 'int' thesofproject/sof#7543](https://github.com/thesofproject/sof/pull/7543)

https://github.com/thesofproject/sof/pull/7544

**Comment by keith-packard** [comment]
The upstream patch has been merged; what's the process for getting that into this repo so it can flow into Zephyr? Do we cherry-pick the patch onto the zephyr branch or merge in the current upstream head?

**Comment by marc-hb** [comment]
I could be wrong but I believe this branch is rebased semi-regularly.

**Comment by keith-packard** [comment]
The required change has been merged upstream. I've merged the current head containing that fix, replacing my int-main branch with that result.

**Comment by joerchan** [comment]
This PR looks misconfigured, surely switching main return type to int is not 328 commits.

**Comment by marc-hb** [comment]
> surely \<X> is not 328 commits.

This is often a sign that the target branch was force-pushed.

**Comment by keith-packard** [comment]
> > surely <X> is not 328 commits.
> 
> This is often a sign that the target branch was force-pushed.

In this case, it looked like the practice for getting upstream changes merged to the Zephyr branch was to pull in the upstream code that contained the change, not just cherry-pick the change over to the Zephyr code. Happy to do a cherry-pick if that is the right plan.

**Comment by cfriedt** [comment]
This looks good - please go ahead and merge (I'm ready to approve https://github.com/zephyrproject-rtos/zephyr/pull/60124)

**Comment by nashif** [comment]
@keith-packard  is this still needed? we synced the sof module and it is now pointing to a commit from yesterday.

**Comment by keith-packard** [comment]
Looks like the sof module has been moved past the commit containing the fix; this PR is now stale.

**Pull request closed without merging**
