### PR TITLE
Update SOF to v2.11

### PR DESCRIPTION
**Pull request by dcpleung**
Update SOF to v2.11, and with some of the patches on renamgin `intel_adsp/ace30_ptl` to `intel_adsp/ace30/ptl`.

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
One note @dcpleung @nashif that I'm not sure whether you want to keep this as a fast-forward compatible branch or not. E.g. we make releases from stable branches so e.g. commit "versions.json: set version to 2.11.0" is not in SOF mainline (only in stable-v2.11 branch). If this is not a problem, PR looks good otherwise.

**Comment by dcpleung** [comment]
Currently we carry a few patches for the `ace30_ptl` to `ace30/ptl` renaming, so we cannot exactly fast-forward commits. So I guess for now this is okay.

**Comment by kv2019i** [comment]
Ack @dcpleung ok. Btw, the ace30 patches were merged to SOF main https://github.com/thesofproject/sof/pull/9475/commits (that will still leave the cmake version patch from @nashif ).

**Comment by nashif** [comment]
> Ack @dcpleung ok. Btw, the ace30 patches were merged to SOF main [thesofproject/sof#9475 (commits)](https://github.com/thesofproject/sof/pull/9475/commits) (that will still leave the cmake version patch from @nashif ).

this cmake version change on the SOF side is a pain

**Comment by nashif** [comment]
did a branch sync, this can be closed now, we are at commit 316f414b64dee8e4aefce503af6c2c2e57d266f4

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@nashif I assume this depends on https://github.com/thesofproject/sof/pull/9577 ? still pending CI check with internal CI.

**Pull request closed without merging**
