### PR TITLE
math/numbers: Rename INT_MAX/INT_MIN -> SOF_INT_MAX/SOF_INT_MIN

### PR DESCRIPTION
**Pull request by keith-packard**
Don't overwrite libc's INT_MIN/INT_MAX values as that ends up breaking usage of UINT_MAX.

Signed-off-by: Keith Packard <keithp@keithp.com>

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@keith-packard thanks, fwiw SOF is transitioning from bare-metal to Zephyr C lib based build hence the redefinition of some macros. 
@singalsu  any reason why we cant use the xtos/Zephyr Kconfig to determine if we define INT_MAX ? I assume our local version is the same as C lib version.

**Review by gmarull — APPROVED** [review]

**Comment by keith-packard** [comment]
> @keith-packard thanks, fwiw SOF is transitioning from bare-metal to Zephyr C lib based build hence the redefinition of some macros. @singalsu any reason why we cant use the xtos/Zephyr Kconfig to determine if we define INT_MAX ? I assume our local version is the same as C lib version.

No, the libc version is just the maximum value of the 'int' type while the SOF version is some bit manipulation macro.

**Comment by singalsu** [comment]
The INT_MIN() seems to be used only in volume component. It would be simpler to use just in SOF just INT32_MIN/MAX and INT16_MIN/MAX there and remove the complicated looking macro. Would that be better?

And dmic driver uses INT_MAX() for non-16/32 bits where the macro makes sense. But it could be renamed. Any suggestions?

**Comment by keith-packard** [comment]
> The INT_MIN() seems to be used only in volume component. It would be simpler to use just in SOF just INT32_MIN/MAX and INT16_MIN/MAX there and remove the complicated looking macro. Would that be better?
> 
> And dmic driver uses INT_MAX() for non-16/32 bits where the macro makes sense. But it could be renamed. Any suggestions?

This isn't my code, so I really don't have any voice here, my only request is that it not conflict with standard C identifiers, like INT_MAX et al.

**Comment by singalsu** [comment]
@lgirdwood What do you recommend? I can do a patch to SOF to rename the conflicting macro (I seem to have contributed to it) if we take that approach.

Edit sorry, confused, this patch does the rename and it looks OK to me.

**Review by singalsu — APPROVED** [review]

**Comment by lgirdwood** [comment]
> @lgirdwood What do you recommend? I can do a patch to SOF to rename the conflicting macro (I seem to have contributed to it) if we take that approach.
> 
> Edit sorry, confused, this patch does the rename and it looks OK to me.

@singalsu we should really use the C lib version where needed and have a new macro like ```INT_MAX_WITH_EXTRA_STUFF()``` where we do any extra work (and this should not be confused with C lib macros).
Are you OK, to make the change in the SOF code where needed to use the C lib version and rename the version we have to be more meaningful.

**Comment by singalsu** [comment]
@lgirdwood Sure, I will make patch for SOF main branch. E.g. INT_MAX_FOR_NUMBER_OF_BITS();

**Comment by lgirdwood** [comment]
> @lgirdwood Sure, I will make patch for SOF main branch. E.g. INT_MAX_FOR_NUMBER_OF_BITS();

Now merged. The manifest can be updated when convenient.

**Comment by keith-packard** [comment]
> > @lgirdwood Sure, I will make patch for SOF main branch. E.g. INT_MAX_FOR_NUMBER_OF_BITS();
> 
> Now merged. The manifest can be updated when convenient.

I've cherry-picked that change from upstream to this branch; is that a reasonable plan?

**Comment by lgirdwood** [comment]
> > > @lgirdwood Sure, I will make patch for SOF main branch. E.g. INT_MAX_FOR_NUMBER_OF_BITS();
> > 
> > 
> > Now merged. The manifest can be updated when convenient.
> 
> I've cherry-picked that change from upstream to this branch; is that a reasonable plan?

@nashif what's your preference ?  I guess we can update to HEAD and update the manifest and realign prior to next Zephyr/SOF releases.

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
ping @nashif @lgirdwood

**Comment by nashif** [comment]
still needed? seems very old and outdated.

**Comment by keith-packard** [comment]
> still needed? seems very old and outdated.

nope, long since merged upstream.

**Pull request closed without merging**
