### PR TITLE
compile: do not use __attribute__((fallthrough)) for XCC

### PR DESCRIPTION
**Pull request by dcpleung**
XCC Clang does not understand __attribute__((fallthrough))
since it is based on Clang 3.9. So do not use this attribute
at all for XCC.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Comment by andyross** [comment]
Given that Cadence didn't give us a good/easy way to identify compilers, maybe a header of our own that cooks it down into something more consumable would be a good idea, yeah.

Though in this particular case, the whole feature is just a warning workaround:  it's so we can use presumptively-more-readable fallthrough cases in switch statements, at the expense of a less readable "__fallthrough" declaration.  Meh.  If we can't do this because of coding standards we should just eat the complexity in code rather than go through dances like this, IMHO.  Would emulating the fallthrough with a goto be OK per the standards?  Probably not.  But IMHO it would be more readable, and surely more portable.

**Review by andyross — APPROVED** [review]
Oh, but +1 obviously

**Comment by dcpleung** [comment]
> @dcpleung Just thinking - do we need to split XCC into XCC_CLANG and XCC_GCC given they both will have some differences and we need to support XCC_GCC for some time to come. ?

On the Zephyr side, there doesn't seem to distinguish between them, _yet_. But it should be easy enough to test for `__XCC__ && __clang__`.

**Review by lgirdwood — APPROVED** [review]

**Comment by dcpleung** [comment]
Use https://github.com/thesofproject/sof/pull/5403 instead.

**Pull request closed without merging**
