### PR TITLE
Update  SOF to latest main from thesofproject

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Update  SOF, from zephyrproject, to latest main from thesofproject

### CODE REVIEW

**Comment by dbaluta** [comment]
> > [](https://docs.zephyrproject.org/latest/guides/modules.html#process-for-submitting-changes-to-existing-modules)
> 
> I added [zephyrproject-rtos/zephyr#38079](https://github.com/zephyrproject-rtos/zephyr/pull/38079)

I don't think you should add a seperate PR for this because it wont help prove that compilation works fine. 

So put the patch at https://github.com/zephyrproject-rtos/zephyr/pull/38079 as last commit in 
https://github.com/zephyrproject-rtos/zephyr/pull/35467

**Comment by nashif** [comment]
> So put the patch at [zephyrproject-rtos/zephyr#38079](https://github.com/zephyrproject-rtos/zephyr/pull/38079) as last commit in
> [zephyrproject-rtos/zephyr#35467](https://github.com/zephyrproject-rtos/zephyr/pull/35467)

I have done that for now.

**Review by lgirdwood — APPROVED** [review]
@nashif this bring up a good point, is there a convention for updating the zephyr SOF module to align it with the main branch on SOF project ? e.g. is this something a bot can do on every SOF merge and where we only manually update the west manifest with good stable commits ?

**Comment by iuliana-prodan** [comment]
> > So put the patch at [zephyrproject-rtos/zephyr#38079](https://github.com/zephyrproject-rtos/zephyr/pull/38079) as last commit in
> > [zephyrproject-rtos/zephyr#35467](https://github.com/zephyrproject-rtos/zephyr/pull/35467)
> 
> I have done that for now.

@nashif sorry, I've missed understood!
Thank you for your help!

**Comment by dbaluta** [comment]
Merged https://github.com/zephyrproject-rtos/sof/pull/12. Now we should update this PR with the hash of the last commit instead of PR number.

**Comment by iuliana-prodan** [comment]
> Merged #12. Now we should update zephyr PR with the hash of the last commit instead of PR number.
> 


I've update the `west.yml` from this PR https://github.com/zephyrproject-rtos/zephyr/pull/35467 with the sha-1 from SOF module instead of pull request number.


> One disturbing thing is the commit numbers are not the same:
> 
> image
> 
> image
> 
> VS
> 
> image
> 
> When I merge #12 I just did rebase + merge? I try to understand if this changed the hashes or they were changed when the PR was created?


I've updated the SOF fork with the latest main, now both repos have the same commit ids - check [thesofproject/main](https://github.com/thesofproject/sof/commits/main) vs. [zephyrproject-rtos/sof/zephyr](https://github.com/zephyrproject-rtos/sof/commits/zephyr).

I believe the problem is on rebase + merge, because when this pull request was created the 3 commits had the same sha-1 as `thesofproject/main`:
image

**Comment by iuliana-prodan** [comment]
> @nashif this bring up a good point, is there a convention for updating the zephyr SOF module to align it with the main branch on SOF project ? e.g. is this something a bot can do on every SOF merge and where we only manually update the west manifest with good stable commits ?

To sync a fork is sufficient to do fetch: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

There is also a possibility for a bot to do the updates automatically. 
Here's an example from openthread: https://github.com/openthread/ot-nrf528xx/commits/main

**Comment by lgirdwood** [comment]
> > @nashif this bring up a good point, is there a convention for updating the zephyr SOF module to align it with the main branch on SOF project ? e.g. is this something a bot can do on every SOF merge and where we only manually update the west manifest with good stable commits ?
> 
> To sync a fork is sufficient to do fetch: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
> 
> There is also a possibility for a bot to do the updates automatically.
> Here's an example from openthread: https://github.com/openthread/ot-nrf528xx/commits/main

I think this needs to mirror exactly and be also be automatic (commit IDs must be the same). I'll discuss with @nashif and @andyross tonight.

**Pull request merged**
