### PR TITLE
sof: common: use Zephyr DIV_ROUND_UP definition

### PR DESCRIPTION
**Pull request by gmarull**
DIV_ROUND_UP is a common macro exposed in public headers without namespacing. Use Zephyr definition to avoid redefinition errors.

Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>

### CODE REVIEW

**Comment by nashif** [comment]
please submit upstream, not something we want to merge here and be stuck with if the sof project has other ideas.

**Comment by gmarull** [comment]
Updated PR with upstream preferences. This needs to go in first, we have an egg or chicken first problem otherwise. Patch can be backported upstream once Zephyr has the macro.

**Review by mbolivar-nordic — APPROVED** [review]

**Review by lgirdwood — COMMENTED** [review]
@gmarull the fix looks fine, but lets pull it in with an update from the main branch (with the other Zephyr integration fixes)

**Comment by gmarull** [comment]
> @gmarull the fix looks fine, but lets pull it in with an update from the main branch (with the other Zephyr integration fixes)

We need to merge this first, otherwise we can't merge the Zephyr changes without breaking CI. I'm not sure why SOF is a module included in Zephyr since it causes circular dependencies like this one, but that is another topic.

**Comment by gmarull** [comment]
This got merged upstream: https://github.com/thesofproject/sof/commit/8c16ce371dbfe4e5b8c31320ad2df849ce4c8a22, who is in charge of syncing this fork?

**Comment by lgirdwood** [comment]
@gmarull I think both fixes are upstream, if you can send a PR to update the fork to SOF HEAD than I think I can merge (if not @nashif)

**Comment by gmarull** [comment]
> @gmarull I think both fixes are upstream, if you can send a PR to update the fork to SOF HEAD than I think I can merge (if not @nashif)

I'm observing a few conflicts when rebasing this repository with upstream sof, likely because this fork has commits not in upstream. Any suggestion?

**Comment by gmarull** [comment]
closing, no longer needed as sof now has a namespaced macro.

**Pull request closed without merging**
